### ISSUE TITLE
App store connect blocking build 

### ISSUE THREAD

**Issue by jshepin** [shah-xad/flutter_tex#45]
Hi, 
My app works perfectly fine on the simulator, and on-device, it builds in xcode, and archives properly too.  Once the build is successfully uploaded to app store connect, I received an email that contains this issue, and the build was blocked after being uploaded and processed by apples servers. I cannot gaurentee this is an issue with this package specifically, because I have no output from them, but I suspect it might be, any usage of "UIWebView" after April 30, 2020 are being blocked -Thanks.
"Dear Developer,
We identified one or more issues with a recent delivery for your app, "Please correct the following issues, then upload again. ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview)."

**Comment by shah-xad** [comment]
You should check other plugins or packages in your application because [flutter_tex](https://pub.dev/packages/flutter_tex) is dependant of [webview_flutter](https://pub.dev/packages/webview_flutter) which is backed by [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) . There's no use of `UIWebView` in this package. See if [this](https://stackoverflow.com/questions/57700996/flutter-how-to-fix-itms-90809-deprecated-api-usage-apple-will-stop-accepting) can help you.
